[GLOBAL]
pants_version = "2.28.0"
backend_packages.add = [
  "pants.backend.experimental.adhoc",
  "pants.backend.shell",
]
build_file_prelude_globs = [
  "pants-macros/*.py",
]

[environments-preview.names]
workspace = "//:workspace"
